// GENERATED by scripts/aip-codegen.mjs — do not edit.
// Source of truth: schemas/aip-1.0.schema.json (generated from crates/interaction-aip).
// Regenerate with `pnpm aip:codegen` from apps/interaction-desktop.
//
// 契約：docs/aip/README.md。驗證行為在 AIPEnvelope.swift，不在這裡。
// 未知的 enum 值一律進 `.unknown(String)`：iPhone 端不得因為桌面版本較新而崩潰或誤判成功。

import Foundation

// MARK: - 任意鍵（保留未知頂層欄位用）

struct AIPAnyCodingKey: CodingKey {
    var stringValue: String
    var intValue: Int? { nil }
    init(stringValue: String) { self.stringValue = stringValue }
    init?(intValue: Int) { nil }
}

/// 十二種 message type。未知值反序列化成 [`MessageType::Unknown`]，**不得執行**（§4.1）。
enum AIPMessageType: Codable, Equatable, Hashable {
    case event
    case command
    case query
    case response
    case result
    case state
    case cancel
    case approvalRequest
    case approvalResult
    case `error`
    case heartbeat
    case capability
    /// 本版不認得的值：保留原字串供稽核，永不執行。
    case unknown(String)

    static let known: [AIPMessageType] = [
        .event,
        .command,
        .query,
        .response,
        .result,
        .state,
        .cancel,
        .approvalRequest,
        .approvalResult,
        .`error`,
        .heartbeat,
        .capability,
    ]

    var rawValue: String {
        switch self {
        case .event: return "event"
        case .command: return "command"
        case .query: return "query"
        case .response: return "response"
        case .result: return "result"
        case .state: return "state"
        case .cancel: return "cancel"
        case .approvalRequest: return "approval-request"
        case .approvalResult: return "approval-result"
        case .`error`: return "error"
        case .heartbeat: return "heartbeat"
        case .capability: return "capability"
        case .unknown(let raw): return raw
        }
    }

    var isKnown: Bool {
        if case .unknown = self { return false }
        return true
    }

    init(rawValue: String) {
        switch rawValue {
        case "event": self = .event
        case "command": self = .command
        case "query": self = .query
        case "response": self = .response
        case "result": self = .result
        case "state": self = .state
        case "cancel": self = .cancel
        case "approval-request": self = .approvalRequest
        case "approval-result": self = .approvalResult
        case "error": self = .`error`
        case "heartbeat": self = .heartbeat
        case "capability": self = .capability
        default: self = .unknown(rawValue)
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// 訊息／能力的參與方種類。未知值 → [`PartyKind::Unknown`]（保留原字串）。
enum AIPPartyKind: Codable, Equatable, Hashable {
    case runtime
    case session
    case device
    case renderer
    case humanSurface
    case human
    case agent
    /// 本版不認得的值：保留原字串供稽核，永不執行。
    case unknown(String)

    static let known: [AIPPartyKind] = [
        .runtime,
        .session,
        .device,
        .renderer,
        .humanSurface,
        .human,
        .agent,
    ]

    var rawValue: String {
        switch self {
        case .runtime: return "runtime"
        case .session: return "session"
        case .device: return "device"
        case .renderer: return "renderer"
        case .humanSurface: return "human-surface"
        case .human: return "human"
        case .agent: return "agent"
        case .unknown(let raw): return raw
        }
    }

    var isKnown: Bool {
        if case .unknown = self { return false }
        return true
    }

    init(rawValue: String) {
        switch rawValue {
        case "runtime": self = .runtime
        case "session": self = .session
        case "device": self = .device
        case "renderer": self = .renderer
        case "human-surface": self = .humanSurface
        case "human": self = .human
        case "agent": self = .agent
        default: self = .unknown(rawValue)
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// 穩定錯誤碼；1.x 內只增不改。未知值保留原字串。
enum AIPErrorCode: Codable, Equatable, Hashable {
    case schemaInvalid
    case unsupportedVersion
    case unsupportedMessageType
    case unknownName
    case unsupportedCapability
    case payloadTooLarge
    case messageTooLarge
    case expired
    case duplicate
    case revisionMismatch
    case sequenceGap
    case identityMismatch
    case notAMember
    case scopeDenied
    case rateLimited
    case sessionNotFound
    case sessionDisabled
    case cancelled
    case `internal`
    /// 本版不認得的值：保留原字串供稽核，永不執行。
    case unknown(String)

    static let known: [AIPErrorCode] = [
        .schemaInvalid,
        .unsupportedVersion,
        .unsupportedMessageType,
        .unknownName,
        .unsupportedCapability,
        .payloadTooLarge,
        .messageTooLarge,
        .expired,
        .duplicate,
        .revisionMismatch,
        .sequenceGap,
        .identityMismatch,
        .notAMember,
        .scopeDenied,
        .rateLimited,
        .sessionNotFound,
        .sessionDisabled,
        .cancelled,
        .`internal`,
    ]

    var rawValue: String {
        switch self {
        case .schemaInvalid: return "schema-invalid"
        case .unsupportedVersion: return "unsupported-version"
        case .unsupportedMessageType: return "unsupported-message-type"
        case .unknownName: return "unknown-name"
        case .unsupportedCapability: return "unsupported-capability"
        case .payloadTooLarge: return "payload-too-large"
        case .messageTooLarge: return "message-too-large"
        case .expired: return "expired"
        case .duplicate: return "duplicate"
        case .revisionMismatch: return "revision-mismatch"
        case .sequenceGap: return "sequence-gap"
        case .identityMismatch: return "identity-mismatch"
        case .notAMember: return "not-a-member"
        case .scopeDenied: return "scope-denied"
        case .rateLimited: return "rate-limited"
        case .sessionNotFound: return "session-not-found"
        case .sessionDisabled: return "session-disabled"
        case .cancelled: return "cancelled"
        case .`internal`: return "internal"
        case .unknown(let raw): return raw
        }
    }

    var isKnown: Bool {
        if case .unknown = self { return false }
        return true
    }

    init(rawValue: String) {
        switch rawValue {
        case "schema-invalid": self = .schemaInvalid
        case "unsupported-version": self = .unsupportedVersion
        case "unsupported-message-type": self = .unsupportedMessageType
        case "unknown-name": self = .unknownName
        case "unsupported-capability": self = .unsupportedCapability
        case "payload-too-large": self = .payloadTooLarge
        case "message-too-large": self = .messageTooLarge
        case "expired": self = .expired
        case "duplicate": self = .duplicate
        case "revision-mismatch": self = .revisionMismatch
        case "sequence-gap": self = .sequenceGap
        case "identity-mismatch": self = .identityMismatch
        case "not-a-member": self = .notAMember
        case "scope-denied": self = .scopeDenied
        case "rate-limited": self = .rateLimited
        case "session-not-found": self = .sessionNotFound
        case "session-disabled": self = .sessionDisabled
        case "cancelled": self = .cancelled
        case "internal": self = .`internal`
        default: self = .unknown(rawValue)
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// `result.payload.status` 的十二種值。
enum AIPOutcome: String, Codable, Equatable, Hashable, CaseIterable {
    case received = "received"
    case accepted = "accepted"
    case acknowledged = "acknowledged"
    case applied = "applied"
    case observed = "observed"
    case claimedCompleted = "claimed-completed"
    case verified = "verified"
    case rejected = "rejected"
    case expired = "expired"
    case cancelRequested = "cancel-requested"
    case cancelConfirmed = "cancel-confirmed"
    case failed = "failed"
}

enum AIPOfflinePolicy: String, Codable, Equatable, Hashable, CaseIterable {
    case dropIfOffline = "drop-if-offline"
    case expireByDeadline = "expire-by-deadline"
    case queueIdempotent = "queue-idempotent"
    case requireReconfirmation = "require-reconfirmation"
    case stateReconcile = "state-reconcile"
}

enum AIPEvidenceClass: String, Codable, Equatable, Hashable, CaseIterable {
    case unit = "unit"
    case contract = "contract"
    case fixture = "fixture"
    case simulator = "simulator"
    case integration = "integration"
    case browser = "browser"
    case realAgent = "real-agent"
    case realDevice = "real-device"
    case realHardware = "real-hardware"
    case unverified = "unverified"
}

/// 參與方角色。
enum AIPMemberRole: String, Codable, Equatable, Hashable, CaseIterable {
    case hostRenderer = "host-renderer"
    case remoteRenderer = "remote-renderer"
    case inputDevice = "input-device"
    case observer = "observer"
}

/// 同步等級（§8／character-session.md §9）。1.0 只實作 `semantic`。
enum AIPSyncClass: String, Codable, Equatable, Hashable, CaseIterable {
    case semantic = "semantic"
    case timeline = "timeline"
    case realtime = "realtime"
}

/// 單一 intent 的協商結果。
enum AIPIntentSupport: String, Codable, Equatable, Hashable, CaseIterable {
    case exact = "exact"
    case unsupported = "unsupported"
}

/// 參與方參照。**只是宣稱**；可信身分由 Transport 綁定後比對（§5）。
struct AIPParty: Codable, Equatable {
    var kind: AIPPartyKind
    var id: String

    private enum Keys: String, CodingKey {
        case kind
        case id
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.kind = try container.decode(AIPPartyKind.self, forKey: .kind)
        self.id = try container.decode(String.self, forKey: .id)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(id, forKey: .id)
    }

    init(
        kind: AIPPartyKind,
        id: String
    ) {
        self.kind = kind
        self.id = id
    }
}

/// AIP 1.0 訊息信封。未知頂層選填欄位保留在 `extra`（round-trip 不遺失、不執行）。
struct AIPEnvelope: Codable, Equatable {
    var specVersion: String
    var messageId: String
    var messageType: AIPMessageType
    var name: String
    var source: AIPParty
    var occurredAt: String
    var baseRevision: UInt64?
    var causationId: String?
    var consentGrantId: String?
    var correlationId: String?
    var expiresAt: String?
    var payload: JSONValue?
    var sequence: UInt64?
    var sessionId: String?
    var target: AIPParty?
    /// 未知的頂層選填欄位：保留、忽略，round-trip 不遺失（AIP §1）。
    var extra: [String: JSONValue] = [:]

    private enum Keys: String, CodingKey, CaseIterable {
        case specVersion
        case messageId
        case messageType
        case name
        case source
        case occurredAt
        case baseRevision
        case causationId
        case consentGrantId
        case correlationId
        case expiresAt
        case payload
        case sequence
        case sessionId
        case target
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.specVersion = try container.decode(String.self, forKey: .specVersion)
        self.messageId = try container.decode(String.self, forKey: .messageId)
        self.messageType = try container.decode(AIPMessageType.self, forKey: .messageType)
        self.name = try container.decode(String.self, forKey: .name)
        self.source = try container.decode(AIPParty.self, forKey: .source)
        self.occurredAt = try container.decode(String.self, forKey: .occurredAt)
        self.baseRevision = try container.decodeIfPresent(UInt64.self, forKey: .baseRevision)
        self.causationId = try container.decodeIfPresent(String.self, forKey: .causationId)
        self.consentGrantId = try container.decodeIfPresent(String.self, forKey: .consentGrantId)
        self.correlationId = try container.decodeIfPresent(String.self, forKey: .correlationId)
        self.expiresAt = try container.decodeIfPresent(String.self, forKey: .expiresAt)
        self.payload = try container.decodeIfPresent(JSONValue.self, forKey: .payload)
        self.sequence = try container.decodeIfPresent(UInt64.self, forKey: .sequence)
        self.sessionId = try container.decodeIfPresent(String.self, forKey: .sessionId)
        self.target = try container.decodeIfPresent(AIPParty.self, forKey: .target)
        let known = Set(Keys.allCases.map(\.rawValue))
        let any = try decoder.container(keyedBy: AIPAnyCodingKey.self)
        var rest: [String: JSONValue] = [:]
        for key in any.allKeys where !known.contains(key.stringValue) {
            rest[key.stringValue] = try any.decode(JSONValue.self, forKey: key)
        }
        self.extra = rest
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encode(specVersion, forKey: .specVersion)
        try container.encode(messageId, forKey: .messageId)
        try container.encode(messageType, forKey: .messageType)
        try container.encode(name, forKey: .name)
        try container.encode(source, forKey: .source)
        try container.encode(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(baseRevision, forKey: .baseRevision)
        try container.encodeIfPresent(causationId, forKey: .causationId)
        try container.encodeIfPresent(consentGrantId, forKey: .consentGrantId)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(payload, forKey: .payload)
        try container.encodeIfPresent(sequence, forKey: .sequence)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(target, forKey: .target)
        var any = encoder.container(keyedBy: AIPAnyCodingKey.self)
        for key in extra.keys.sorted() {
            guard let value = extra[key] else { continue }
            try any.encode(value, forKey: AIPAnyCodingKey(stringValue: key))
        }
    }

    init(
        specVersion: String,
        messageId: String,
        messageType: AIPMessageType,
        name: String,
        source: AIPParty,
        occurredAt: String,
        baseRevision: UInt64? = nil,
        causationId: String? = nil,
        consentGrantId: String? = nil,
        correlationId: String? = nil,
        expiresAt: String? = nil,
        payload: JSONValue? = nil,
        sequence: UInt64? = nil,
        sessionId: String? = nil,
        target: AIPParty? = nil,
        extra: [String: JSONValue] = [:]
    ) {
        self.specVersion = specVersion
        self.messageId = messageId
        self.messageType = messageType
        self.name = name
        self.source = source
        self.occurredAt = occurredAt
        self.baseRevision = baseRevision
        self.causationId = causationId
        self.consentGrantId = consentGrantId
        self.correlationId = correlationId
        self.expiresAt = expiresAt
        self.payload = payload
        self.sequence = sequence
        self.sessionId = sessionId
        self.target = target
        self.extra = extra
    }
}

/// `error.payload`。`message` ≤ 200 字、不回顯輸入；`details` 不得含 secret／路徑／token。
struct AIPErrorPayload: Codable, Equatable {
    var code: AIPErrorCode
    var message: String
    var retryable: Bool
    var details: [String: JSONValue]?

    private enum Keys: String, CodingKey {
        case code
        case message
        case retryable
        case details
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.code = try container.decode(AIPErrorCode.self, forKey: .code)
        self.message = try container.decode(String.self, forKey: .message)
        self.retryable = try container.decode(Bool.self, forKey: .retryable)
        self.details = try container.decodeIfPresent([String: JSONValue].self, forKey: .details)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encode(retryable, forKey: .retryable)
        try container.encodeIfPresent(details, forKey: .details)
    }

    init(
        code: AIPErrorCode,
        message: String,
        retryable: Bool,
        details: [String: JSONValue]? = nil
    ) {
        self.code = code
        self.message = message
        self.retryable = retryable
        self.details = details
    }
}

struct AIPCapabilityLimits: Codable, Equatable {
    var maxMessageBytes: Int?

    private enum Keys: String, CodingKey {
        case maxMessageBytes
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.maxMessageBytes = try container.decodeIfPresent(Int.self, forKey: .maxMessageBytes)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encodeIfPresent(maxMessageBytes, forKey: .maxMessageBytes)
    }

    init(
        maxMessageBytes: Int? = nil
    ) {
        self.maxMessageBytes = maxMessageBytes
    }
}

/// `capability` 宣告 payload（member → host）。未知鍵保留在 `extra`。
struct AIPCapabilityAnnouncement: Codable, Equatable {
    var features: [String: JSONValue]?
    /// 可產生的 event name。
    var inputs: [String]?
    /// 可呈現的 Behavior Intent 名稱。
    var intents: [String]?
    var limits: AIPCapabilityLimits?
    var profiles: [String]?
    var role: AIPMemberRole?
    var specVersions: [String]?
    var syncClasses: [AIPSyncClass]?

    private enum Keys: String, CodingKey {
        case features
        case inputs
        case intents
        case limits
        case profiles
        case role
        case specVersions
        case syncClasses
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.features = try container.decodeIfPresent([String: JSONValue].self, forKey: .features)
        self.inputs = try container.decodeIfPresent([String].self, forKey: .inputs)
        self.intents = try container.decodeIfPresent([String].self, forKey: .intents)
        self.limits = try container.decodeIfPresent(AIPCapabilityLimits.self, forKey: .limits)
        self.profiles = try container.decodeIfPresent([String].self, forKey: .profiles)
        self.role = try container.decodeIfPresent(AIPMemberRole.self, forKey: .role)
        self.specVersions = try container.decodeIfPresent([String].self, forKey: .specVersions)
        self.syncClasses = try container.decodeIfPresent([AIPSyncClass].self, forKey: .syncClasses)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encodeIfPresent(features, forKey: .features)
        try container.encodeIfPresent(inputs, forKey: .inputs)
        try container.encodeIfPresent(intents, forKey: .intents)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(profiles, forKey: .profiles)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(specVersions, forKey: .specVersions)
        try container.encodeIfPresent(syncClasses, forKey: .syncClasses)
    }

    init(
        features: [String: JSONValue]? = nil,
        inputs: [String]? = nil,
        intents: [String]? = nil,
        limits: AIPCapabilityLimits? = nil,
        profiles: [String]? = nil,
        role: AIPMemberRole? = nil,
        specVersions: [String]? = nil,
        syncClasses: [AIPSyncClass]? = nil
    ) {
        self.features = features
        self.inputs = inputs
        self.intents = intents
        self.limits = limits
        self.profiles = profiles
        self.role = role
        self.specVersions = specVersions
        self.syncClasses = syncClasses
    }
}

/// host 回的協商結果（`capability` payload，host → member）。
struct AIPNegotiatedCapabilities: Codable, Equatable {
    var specVersion: String
    var newerMinor: Bool
    var role: AIPMemberRole
    var syncClass: AIPSyncClass
    var intents: [String: AIPIntentSupport]
    var inputs: [String]
    var unsupportedInputs: [String]
    var limits: AIPCapabilityLimits

    private enum Keys: String, CodingKey {
        case specVersion
        case newerMinor
        case role
        case syncClass
        case intents
        case inputs
        case unsupportedInputs
        case limits
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Keys.self)
        self.specVersion = try container.decode(String.self, forKey: .specVersion)
        self.newerMinor = try container.decode(Bool.self, forKey: .newerMinor)
        self.role = try container.decode(AIPMemberRole.self, forKey: .role)
        self.syncClass = try container.decode(AIPSyncClass.self, forKey: .syncClass)
        self.intents = try container.decode([String: AIPIntentSupport].self, forKey: .intents)
        self.inputs = try container.decode([String].self, forKey: .inputs)
        self.unsupportedInputs = try container.decode([String].self, forKey: .unsupportedInputs)
        self.limits = try container.decode(AIPCapabilityLimits.self, forKey: .limits)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Keys.self)
        try container.encode(specVersion, forKey: .specVersion)
        try container.encode(newerMinor, forKey: .newerMinor)
        try container.encode(role, forKey: .role)
        try container.encode(syncClass, forKey: .syncClass)
        try container.encode(intents, forKey: .intents)
        try container.encode(inputs, forKey: .inputs)
        try container.encode(unsupportedInputs, forKey: .unsupportedInputs)
        try container.encode(limits, forKey: .limits)
    }

    init(
        specVersion: String,
        newerMinor: Bool,
        role: AIPMemberRole,
        syncClass: AIPSyncClass,
        intents: [String: AIPIntentSupport],
        inputs: [String],
        unsupportedInputs: [String],
        limits: AIPCapabilityLimits
    ) {
        self.specVersion = specVersion
        self.newerMinor = newerMinor
        self.role = role
        self.syncClass = syncClass
        self.intents = intents
        self.inputs = inputs
        self.unsupportedInputs = unsupportedInputs
        self.limits = limits
    }
}

// MARK: - 常數（AIP §11／§12）

enum AIPConstants {
    /// 本實作宣告的 spec 版本。major 不同一律拒絕。
    static let specVersion = "aip/1.0"
    /// 十二種 message type（AIP §2.1）。
    static let messageTypes: [String] = [
        "event",
        "command",
        "query",
        "response",
        "result",
        "state",
        "cancel",
        "approval-request",
        "approval-result",
        "error",
        "heartbeat",
        "capability",
    ]
    /// 穩定錯誤碼（AIP §12）。
    static let errorCodes: [String] = [
        "schema-invalid",
        "unsupported-version",
        "unsupported-message-type",
        "unknown-name",
        "unsupported-capability",
        "payload-too-large",
        "message-too-large",
        "expired",
        "duplicate",
        "revision-mismatch",
        "sequence-gap",
        "identity-mismatch",
        "not-a-member",
        "scope-denied",
        "rate-limited",
        "session-not-found",
        "session-disabled",
        "cancelled",
        "internal",
    ]
}

/// 上限常數（AIP §11）。所有集合、訊息、字串都有界。
enum AIPLimits {
    static let dedupeRing = 256
    static let defaultIntentTtlMs = 10000
    static let defaultInteractionTtlMs = 5000
    static let eventLogRing = 512
    static let maxClockSkewMs = 30000
    static let maxIdChars = 128
    static let maxJsonDepth = 8
    static let maxMembers = 16
    static let maxMessageBytes = 65536
    static let maxNameChars = 128
    static let maxPayloadBytes = 32768
    static let maxStringChars = 2000
}
