import json, pathlib
base = pathlib.Path(".")
md = (base / "e2e-baseline-draft.md").read_text(encoding="utf-8")

table = [
 {"id":"E0-01","scenario":"首次設定精靈完成＋UI 偏好變更，daemon/App 重啟後仍保留；native 端另加 10 種注入故障後的預設恢復",
  "claudeCode":"n/a（不涉及 agent session）","codex":"n/a（不涉及 agent session）","fixture":"n/a",
  "nativeDesktop":"completed（10/10 故障案例收斂，113.66 s；但 App 為 2026-09-06 的 0.7.0 bundle，非 HEAD build）",
  "realIphone":"n/a","overall":"completed",
  "evidence":"runs/R5/E0-01-step{1,2,3}.log；runs/R5/E0-11-restart-check.log；runs/R7/preset/result.json（$.results[*].status 全 completed）；runs/R7/preset.cmd.txt EXIT=0"},
 {"id":"E0-02","scenario":"派工給真 agent 並比對 ground truth；延伸：同 session 多輪與 resumeProviderSessionId 原生續接（K-04）",
  "claudeCode":"completed：答案逐字正確、claimed-completed、spentCost 0.14471075；多輪不重新 spawn（pid 33355 不變）；續接 argv 直接證據 --resume <psid>，provider log 續寫同一檔且 prompt 不含暗號",
  "codex":"completed（--approve approve 走完，答案逐字正確）／correctly-blocked（不核可則停在 waiting-for-consent，spentCost=0.0）；多輪 pid 35908 不變；thread/resume 續寫同一 rollout 且 read-only/untrusted 重新上鎖",
  "fixture":"n/a（native work driver 從未真的啟動 fixture agent）",
  "nativeDesktop":"harness-failed（composer 打字被截斷，未曾送出工作）","realIphone":"n/a","overall":"completed",
  "evidence":"e2e/claude-smoke-1/{result.json,sse.jsonl}；e2e/codex-smoke-{1,2}/result.json；runs/R8/claude/{run.log,raw.json,sse.jsonl}；runs/R8/argv-claude/run.log:5；runs/R8/codex/raw.json；~/.claude/projects/.../e63b51f8-....jsonl；~/.codex/sessions/2026/09/07/rollout-...-01a07b22-....jsonl"},
 {"id":"E0-03","scenario":"對進行中的工作按下取消／關閉／緊急停止，驗證分類誠實度、子程序死亡與重啟後不自動恢復",
  "claudeCode":"product-failed：interrupt 一律 failed（5/5 重現，含 active 時取消）；grep -c TaskCancelled claude.rs == 0。close(from active)→closed 為 completed；estop 全部不變量成立（completed）",
  "codex":"completed：interrupt→cancelled（3/3，rollout turn_aborted 獨立佐證）；close→closed",
  "fixture":"n/a","nativeDesktop":"harness-failed（兩次都卡在 AX composer 輸入，截斷點不同、osascript 皆 exit 0）",
  "realIphone":"n/a","overall":"product-failed",
  "evidence":"runs/R1/claude-interrupt/{result.json,sse.jsonl:109,116}；runs/R1/codex-interrupt/sse.jsonl:103；runs/R1/b07-{claude,codex}/result.json（task2Status=409）；runs/R1/a07-claude/result.json；e2e/claude-cancel-1/home/state/interaction.db（error_during_execution）；runs/R7/work{,-diag1}/failed-ax.txt:40"},
 {"id":"E0-04","scenario":"daemon 被 SIGKILL 後重啟：session 狀態誠實度、mailbox/lease 邊界、孤兒子程序回收",
  "claudeCode":"completed：expired＋detail 記錄回收 pgid 15721；SIGKILL 後子程序 ppid=1，重啟後 children=[]；send 409／interrupt 404／renew 409",
  "codex":"completed：codex 隨 daemon 死亡（stdin 關閉），rollout 於 5 ms 後記 turn_aborted；detail 無 pgid（無孤兒可歸因）",
  "fixture":"n/a","nativeDesktop":"n/a","realIphone":"n/a",
  "overall":"completed（SIGTERM 乾淨關閉路徑本輪未跑＝harness-failed；原判 needs-environment → 改判 harness-failed，理由：restart_test.py --signal TERM 在同機同 binary 可用，不是環境缺口）",
  "evidence":"e2e/restart-claude-kill/{result.json,daemon.log}；e2e/restart-codex-kill/result.json；~/.codex/sessions/2026/09/07/rollout-...-01a07a04-....jsonl；crates/interaction-runtime/src/agents.rs:1479-1520,1615-1671"},
 {"id":"E0-05","scenario":"記憶建立→Context Bundle→真 agent 讀取→矛盾記憶→刪除→舊 provider transcript 是否仍記得（E-09）→重啟保留→受限 token 降權",
  "claudeCode":"completed：bundle 送達且被讀（summary 含暗號）；刪除後 includes=[] 且誠實說不知道；resume 後完整覆誦已刪除的機密暗號（E-09 成立，刪除不可回收）",
  "codex":"not-run（codex 的 E-09 等價行為本輪完全未測）",
  "fixture":"n/a","nativeDesktop":"n/a","realIphone":"n/a","overall":"completed",
  "evidence":"runs/R2/step{1,2,4,5,6,7}-*.json；runs/R2/E0-05-delivery-claude/result.json；~/.claude/projects/.../1bf60429-....jsonl:20；crates/interaction-core/src/memory.rs:166-180"},
 {"id":"E0-06","scenario":"同一 daemon 下兩個同型 session 併發：隔離、取消獨立性、記錄不靜默遺失；併發上限",
  "claudeCode":"completed（claude×2：0 筆 SSE sessionId 混淆、無暗號交叉、取消不干擾另一個）",
  "codex":"completed（codex×2：核可只作用於 i=0，0 筆混淆）",
  "fixture":"n/a","nativeDesktop":"n/a","realIphone":"n/a",
  "overall":"completed（併發上限 max_sessions=8／max_parallel=4：needs-environment。原判 not-implemented → 改判 needs-environment，理由：功能在 agent.rs:124-146 與 agents.rs:490/496 確實實作，只是本輪最多跑 2 個並行 session）",
  "evidence":"e2e/multi-C-claude-x2/{result.json,sse.jsonl}；e2e/multi-D-codex-x2/{result.json,sse.jsonl}；crates/interaction-core/src/agent.rs:124-146；crates/interaction-runtime/src/agents.rs:490,496"},
 {"id":"E0-07","scenario":"claude-code 與 codex 跨型並行，取消其中的 claude session",
  "claudeCode":"完成其取消（但終態 failed，見 D1）","codex":"completed：不受影響，照常走完核可循環並回報自己的暗號",
  "fixture":"n/a","nativeDesktop":"n/a","realIphone":"n/a","overall":"completed",
  "evidence":"e2e/multi-E-claude-codex/{result.json,sse.jsonl}；~/.claude/projects/.../276c9883-....jsonl；~/.codex/sessions/.../rollout-...-01a07a03-....jsonl"},
 {"id":"E0-08","scenario":"iPhone：配對＋能力協商、雙向狀態、停止結果未知的誠實度、AIP 互動、斷線重連 resume、撤銷、核心離線後重連",
  "claudeCode":"n/a","codex":"n/a",
  "fixture":"completed（配對／雙向／stop-unknown＋unresolved／AIP revision 1→3／reconnect patches／revoke 立即斷線且舊 token 被拒）；F-06 daemon 側 completed，但出貨 fixture 在連線被拒時 process::exit(2)（fake_iphone.rs:177←:298）→ 裝置側 harness-failed，改用自寫 WS probe 驗證",
  "nativeDesktop":"harness-failed（4/10 與 6/10 journey 後 AX dump 超過 55 s 上限；四個 sensor journey 從未跑到）",
  "realIphone":"needs-environment（裝置 available (paired)＋Developer Mode enabled，但 Xcode IDEProvisioningTeams 為空，device-build.sh 卡在 step 3/5）",
  "overall":"completed（fixture 範圍）／needs-environment（真機）",
  "evidence":"runs/R6/logs/{pair-2.json,phone.log:1-27,phone2.stderr.log,phone3.log:4-6,daemon-responses.jsonl,probe-{while-dead,after-restart}.json}；runs/R7/mobile{,-diag1}/result.json；apps/interaction-ios/scripts/device-build.sh:158-190"},
 {"id":"E0-09","scenario":"agent 需要人類補充資訊時的非同步問答；waiting-for-input 是否會被自動偵測",
  "claudeCode":"completed（多輪續談：澄清問句→claimed-completed→人類回答→同 session 第二輪延續脈絡）",
  "codex":"completed（同型行為，且拍到 staleClaim→active→新 claimId 的中間態）",
  "fixture":"n/a","nativeDesktop":"n/a（UI 投影只讀 workState.ts:91-101 常數表，未跑 Tauri/Playwright）","realIphone":"n/a",
  "overall":"not-implemented（自動偵測不存在：TaskWaitingForInput 只有定義與消費點，沒有任何連接器產生；人工 POST /report 路徑 completed）",
  "evidence":"crates/interaction-agent-gateway/src/lib.rs:99；crates/interaction-runtime/src/gateway.rs:412-417；runs/R3/{claude-followup,codex-followup,manual-report}/result.json；apps/interaction-desktop/src/statusProjection/workState.ts:91-101"},
 {"id":"E0-10","scenario":"權限：唯讀阻擋、人類拒絕核可、授權寫入＋human verify、撤銷、TTL 過期、AI 不可授權、續開不得放寬",
  "claudeCode":"correctly-blocked（唯讀：provider 端連 Write 工具都沒給，permissionMode=plan）／completed（授權寫入：permissionMode=acceptEdits，hello.txt 落地，verify 後 humanVerified 綁 claimId，重複 verify 409）",
  "codex":"completed（阻擋有效、accept 路徑檔案落地）＋product-failed（deny 送 \"reject\"，不在 codex 0.153.4 列舉內，人類否決在 agent 端變成 approval request failed）；另 writable_roots 併入使用者全域設定，超出 session 授權範圍",
  "fixture":"n/a","nativeDesktop":"n/a","realIphone":"n/a",
  "overall":"correctly-blocked（撤銷／過期／續開不放寬／agent token 全部確定性阻擋；deny 語意有 product-failed 缺陷）",
  "evidence":"runs/R4/{a-codex-deny,b-claude,b-codex,c-claude-write,c-codex-write,d-revoke,d-resume,d-resume2,e-ttl,f-agent-token}/*；runs/R8/{guard-claude,guard-codex}/run.log；crates/interaction-agent-gateway/src/codex.rs:643-644；~/.codex/config.toml:418-419"},
 {"id":"E0-11","scenario":"備份匯出範圍聲明、重啟保留、在全新 home 還原、壞資料還原被擋；native 端真下載＋真 NSOpenPanel",
  "claudeCode":"n/a","codex":"n/a","fixture":"n/a",
  "nativeDesktop":"harness-failed（匯出這一半真的驗到：~/Downloads 404 bytes sha256 f4a3171…；匯入與四個阻擋案例全部未驗證，AX choosefile 從不驗證導航，Open panel 停在 2026-09-06 的記憶目錄→2026-09-06 那次綠燈可能是假陽性）",
  "realIphone":"n/a",
  "overall":"completed（API/CLI 範圍）＋correctly-blocked（壞資料 400）＋harness-failed（native 匯入）",
  "evidence":"runs/R5/{E0-11-export-api.json,E0-11-export-cli.json,E0-11-export-api-vs-cli-diff.log,E0-11-restore-fresh-field-diff.log,E0-11-bad-backup.json,E0-11-restore-bad-item.log}；runs/R7/settings/{result.json,failed-ax.txt}；runs/R7/probe5/main-window-final.txt:225"},
]

defects = [
 {"id":"D1","title":"人類 interrupt 真 claude-code session → 終態 failed 而非 cancelled；Claude 連接器在任何路徑都產不出 cancelled",
  "severity":"high",
  "location":"crates/interaction-agent-gateway/src/claude.rs:354-357（interrupt 只送 SIGINT，不留取消旗標）＋claude.rs:442-455（result/subtype 以 error 開頭 → TaskFailed）＋claude.rs:213-231（TaskFailed 設 saw_result，讓 :267-283 的誠實退路失效）→ crates/interaction-runtime/src/gateway.rs:579-584 → crates/interaction-runtime/src/agents.rs:1185",
  "repro":"python3 <harness>/agent_smoke.py --agent claude-code --port N --out DIR --task '<1500 字長文>' --cancel-after 3 --cancel-when-active --cancel-mode interrupt → final state 'failed'（期望 'cancelled'）；同旗標換 --agent codex → 'cancelled'",
  "evidence":["runs/R1/claude-interrupt/result.json（cancel-issued 09:05:00.474 → state failed 09:05:01.002）","runs/R1/claude-interrupt/sse.jsonl:109 state=failed、:102 character.system-text intent=failed「動作失敗。」","runs/R1/b07-claude/result.json events[k=p1-terminal].state='failed'（獨立第二次）","e2e/{claude-cancel-1,multi-C-claude-x2,multi-E-claude-codex}/result.json（另外三次重現）","e2e/claude-cancel-1/home/state/interaction.db obs-93f1d928 inferences.report.error='error_during_execution'","~/.claude/projects/.../5779447a-....jsonl:9 '[Request interrupted by user]'（provider 自己認定是使用者中斷）","grep -c TaskCancelled crates/interaction-agent-gateway/src/claude.rs == 0","crates/interaction-agent-gateway/src/codex_exec.rs:253-258/320-329（同 repo 內已有正確做法：先 set cancel_requested 再送訊號）","crates/interaction-runtime/tests/gateway_loop.rs:1826-1829 'an interrupted turn is neither a claim nor a failure'（此契約只有 codex 有測試）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D2","title":"close 的 SSE 投影把已終結的 failed/timed-out/unknown 一律壓成 'closed'，與刻意保留終局狀態的 record 互相矛盾",
  "severity":"high",
  "location":"crates/interaction-runtime/src/agents.rs:1371-1379（只特判 Cancelled，其餘落到 \"closed\"）對照 agents.rs:1296-1310（record 刻意保留前一個終局狀態，並有反回歸註解）",
  "repro":"中斷一個 claude session（state→failed），再 POST /v1/agent-sessions/{id}/close {\"reason\":\"...\"}；close 回應與之後的 GET 都是 'failed'，但同一瞬間發出的 SSE agent.session.state 是 'closed'",
  "evidence":["runs/R1/claude-interrupt/sse.jsonl:116 state='closed' @2026-09-07T09:05:07.606889Z","runs/R1/claude-interrupt/result.json final.state='failed'、detail='phase0 close after cancel (was Failed)'、closedAt=09:05:07.598639Z（同一瞬間）","runs/R1/codex-interrupt/sse.jsonl:109 state='cancelled'（Cancelled 是唯一被保留的終局狀態）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D3","title":"failed 的 agent session 在 record 與 mailbox 上都沒有任何原因；唯一線索只存在於 observation（原始 provider token 'error_during_execution'）",
  "severity":"medium",
  "location":"crates/interaction-runtime/src/agents.rs:1209-1218（report_agent_session 只設 state，從不寫 entry.record.detail；錯誤 payload 只進 ingest(\"agent.session\", …)，見 agents.rs:1254-1257）",
  "repro":"中斷一個進行中的 claude session，然後 GET /v1/agent-sessions/{id} → {\"state\":\"failed\"} 且無 detail 欄；GET .../messages?direction=from-session → []；只有 observations 查詢才看得到 error_during_execution",
  "evidence":["runs/R1/b07-claude/result.json p1Terminal（完整 record，state='failed'，無 detail key）","runs/R1/diag-failreason/result.json events[k=record] detail=null、mailbox from-session count=0、audit-exit-mentions count=0，observations 最新 inferences.report.error='error_during_execution'"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D4","title":"Codex 核可拒絕送出的 wire 值 \"reject\" 不在 codex 0.153.4 的 CommandExecutionApprovalDecision 列舉內；人類的「拒絕」在 agent 端變成核可機制錯誤而非語意上的拒絕",
  "severity":"medium",
  "location":"crates/interaction-agent-gateway/src/codex.rs:643-644（Approve => \"accept\"、Deny => \"reject\"）",
  "repro":"unset INTERACT_AI_CLAUDE_BIN INTERACT_AI_CODEX_BIN; python3 <harness>/agent_smoke.py --agent codex --port N --out DIR --approve deny --task '請讀取 NOTES.md 並回答第一個標題。' --timeout 90；再讀 ~/.codex/sessions/YYYY/MM/DD/rollout-*-<psid>.jsonl 的 custom_tool_call_output",
  "evidence":["matrix/codex-schema-0.153.4/CommandExecutionRequestApprovalResponse.json → oneOf 只有 accept/acceptForSession/acceptWithExecpolicyAmendment/applyNetworkPolicyAmendment/decline/cancel","strings -a /opt/homebrew/Caskroom/codex/0.153.4/bin/codex | grep acceptForSession → 'acceptacceptForSessiondeclinecancel'，binary 內無 reject 變體","~/.codex/sessions/2026/09/07/rollout-...-01a07b1c-3dda-....jsonl:15 output 'exec_command failed: CreateProcess { message: \"Rejected(\\\"approval request failed\\\")\" }'","runs/R4/a-codex-deny/result.json messages-from-session[2].body.summary（agent 把 approval request failed 原文轉述給人類）","對照組 runs/R4/c-codex-write（accept 為合法值 → 指令真的執行、檔案落地）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D5","title":"codex 連接器沒有等價於 claude 的 MCP／plugin 封鎖：宣告唯讀的 session 一建立就啟動使用者 ~/.codex 設定裡的 MCP server（chrome-devtools-mcp 瀏覽器控制、codegraph）與 ChatGPT computer-use helper，且任務全文出現在 world-readable 的 process argv",
  "severity":"high",
  "location":"crates/interaction-agent-gateway/src/codex.rs:166-169（只設 current_dir，無任何 MCP/plugin 限制）對照 claude.rs:82-84（--strict-mcp-config --mcp-config {\"mcpServers\":{}}）",
  "repro":"cd <R8 out>; unset INTERACT_AI_CLAUDE_BIN INTERACT_AI_CODEX_BIN; python3 psleak_probe.py \"$PWD/psleak\" 19086（建立 allowWrite=false／toolScope=[] 的 codex session，送含唯一標記的唯讀任務，同時每 80 ms 掃 ps -axww -o pid=,ppid=,command=）",
  "evidence":["runs/R8/argv-codex/run.log:9 子程序 node .../npx -y chrome-devtools-mcp@latest（ppid = codex app-server）","runs/R8/argv-codex/run.log:10 node .../codegraph serve --mcp","runs/R8/argv-codex/run.log:11 ChatGPT.app unified-computer-use launch.mjs","runs/R8/psleak/raw.json $.psHits[0].line 含唯一標記 PSLEAKHTYB7B72 與完整 input-messages","runs/R8/argv-claude/run.log:5（對照組：claude argv 有 --strict-mcp-config）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"1"},
 {"id":"D6","title":"allowWrite 的 codex session 只送 sandbox:\"workspace-write\" 字串、不送 writable_roots，實際生效範圍併入使用者全域 ~/.codex/config.toml，超出 session 授權的 resolvedWorkdir",
  "severity":"medium",
  "location":"crates/interaction-agent-gateway/src/codex.rs:315-340（thread/start 與 thread/resume 的 params 只有 cwd／approvalPolicy／sandbox 字串）",
  "repro":"在 ~/.codex/config.toml 設 [sandbox_workspace_write] writable_roots=[...]；用 --allow-write 建 codex session 送任務；讀 rollout 的 turn_context.payload.sandbox_policy",
  "evidence":["~/.codex/sessions/2026/09/07/rollout-...-01a07b1e-21d9-....jsonl turn_context.sandbox_policy.writable_roots=['/Users/user/.agents/skills/agmsg/db','.../teams','.../run']","~/.codex/config.toml:418-419 [sandbox_workspace_write] writable_roots（逐項相同）","crates/interaction-agent-gateway/src/codex.rs:315-340（params 無 writable_roots 欄位）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
 {"id":"D7","title":"codex.rs 把所有帶 id+method 的 ServerRequest 一律當核可請求，不分辨 item/tool/requestUserInput；resolve_approval 一律回 {result:{decision}}，與 ToolRequestUserInputResponse 的 {answers:{…}} 合約不符，問題文字也被丟棄",
  "severity":"medium",
  "location":"crates/interaction-agent-gateway/src/codex.rs:250-263（(true, Some(m)) 分支不 dispatch method）＋codex.rs:432-445（approval_summary 只找 command/cmd/path/reason）＋codex.rs:623-660（resolve_approval 的回應 shape）",
  "repro":"讓 codex app-server 對某 thread 送出 method=item/tool/requestUserInput 的 ServerRequest（本輪兩次真 turn 都未自然觸發，EXPERIMENTAL）；靜態比對 codex.rs:646-650 送出的 JSON 與 codex-schema-0.153.4/ToolRequestUserInputResponse.json 必填欄位",
  "evidence":["crates/interaction-agent-gateway/src/codex.rs:249-266,431-445,623-660（直接讀碼確認）","codex-schema-0.153.4/ServerRequest.json:1898-1919（item/tool/requestUserInput）","codex-schema-0.153.4/ToolRequestUserInputParams.json / ToolRequestUserInputResponse.json"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
 {"id":"D8","title":"沒有『停止這一輪、保留 session』的能力：POST /interrupt 在兩個 agent 上都是 session 級取消，之後送任務一律 409 mailbox closed，子程序也已被殺",
  "severity":"medium",
  "location":"crates/interaction-runtime/src/agents.rs:900-904（state 非 open 即拒絕）＋crates/interaction-runtime/src/gateway.rs:579-588（interrupt 轉成終局回報而非只結束 turn）",
  "repro":"python3 <R1 out>/bin/b07.py --agent claude-code --port 19014 --out DIR（與 --agent codex --port 19015）：長任務 → 等 active → POST /interrupt → 等終態 → POST .../messages {kind:task}",
  "evidence":["runs/R1/b07-claude/result.json task2Status=409 'agent session ... is Failed; mailbox closed'","runs/R1/b07-codex/result.json task2Status=409 '... is Cancelled; mailbox closed'","runs/R1/b07-claude/result.json events[k=children-final].children=[]（子程序樹已消失，無法就地續跑）","~/.codex/sessions/.../rollout-...-01a07b21-....jsonl turn_aborted reason=interrupted（provider 端其實只中止 turn，是 runtime 選擇殺掉整個 session）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"3"},
 {"id":"D9","title":"續開授權檢查（check_resume_not_wider／check_resume_same_workdir）無論拒絕或接受都不留稽核紀錄；被接受的續開也沒有記下接續了哪一個 provider session",
  "severity":"medium",
  "location":"crates/interaction-runtime/src/agents.rs:453-468（resume guard 直接 return Err(PolicyBlocked)，整段沒有 store.audit 呼叫；check_resume_not_wider 於 :105、check_resume_same_workdir 於 :204 同樣無 audit）",
  "repro":"cd <R8 out>; python3 guard_probe.py --agent claude-code --port 19084 --home \"$PWD/claude/home\" --workdir \"$PWD/claude/workdir\" --resume-id <psid> --out \"$PWD/guard-claude\"；7 個放寬形狀 403 之後 GET /v1/audit 找不到任何對應紀錄",
  "evidence":["runs/R8/guard-claude/raw.json $.auditAfter（47 筆，kinds 只有 character.session.truth／character.system-text／agent-session.closed／agent-session.capability-issued）","runs/R8/claude/raw.json $.auditTail（23 筆，同樣沒有 resume/policy_blocked）","crates/interaction-runtime/src/agents.rs:453-468（直接讀碼確認無 audit）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"1"},
 {"id":"D10","title":"agent.session.state 的 SSE 投影混用 gateway 階段名（fetched／working）與真實 record 狀態，導致同一時刻 GET 說 created、SSE 說 fetched",
  "severity":"low",
  "location":"crates/interaction-runtime/src/gateway.rs:798（emit \"fetched\"）與 crates/interaction-runtime/src/agents.rs:1060（\"working\"）；AgentSessionRecord 沒有對應狀態",
  "repro":"建立任一 claude session 並送任務，同時開 SSE 與每 0.5 s GET /v1/agent-sessions/{id}：整整約 60 s 內 GET 回 'created' 而 SSE 已是 'fetched'",
  "evidence":["runs/R1/claude-interrupt/result.json（task-sent 到 active 61.3 s，期間 GET 一律 created）","e2e/claude-cancel-1/sse.jsonl id=99 state='fetched'（record 無此狀態）","apps/interaction-desktop/src/statusProjection/workState.ts（兩個值都被投影成「準備中」，因此不造成錯誤呈現，但『取消當下是什麼狀態』有兩個答案）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
 {"id":"D11","title":"waiting-for-input 沒有任何連接器會自動產生：GatewayEvent::TaskWaitingForInput 只有定義與單一消費點，UI 的 NEEDS_INPUT 投影永遠不會被觸發，只能靠人工 POST /report",
  "severity":"medium",
  "location":"crates/interaction-agent-gateway/src/lib.rs:99（定義＋自陳註解）；crates/interaction-runtime/src/gateway.rs:412-417（唯一消費點）；crates/interaction-runtime/src/agents.rs:1182,1248（waiting-for-input 只走人工回報路徑）",
  "repro":"grep -rn TaskWaitingForInput crates/ → 只有定義與消費點；跑任一真 agent 的澄清問答（runs/R3/claude-followup）→ 澄清問句被包成 claimed-completed，從未出現 waiting-for-input",
  "evidence":["crates/interaction-agent-gateway/src/lib.rs:92-99","crates/interaction-runtime/src/gateway.rs:412-417","runs/R3/claude-followup/result.json（turn1 終態 claimed-completed，summary 是澄清問句）","apps/interaction-desktop/src/statusProjection/workState.ts:91-101（NEEDS_INPUT 投影已存在）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
 {"id":"D12","title":"受限 agent token 按下 emergency stop 會把 claimed-completed 的 session 轉成 cancelled，人類之後再也無法對那個聲稱做 verify（409）",
  "severity":"low",
  "location":"crates/interaction-api/src/lib.rs:454-461（agent token 允許 POST /v1/emergency-stop）＋crates/interaction-runtime/src/agents.rs:1120-1150（只有 claimed-completed 可 verify）",
  "repro":"建一個 claude session 跑到 claimed-completed（先不 verify）→ 用 <home>/state/api-agent-token POST /v1/emergency-stop → GET session 變 cancelled（detail='cancelled (was ClaimedCompleted)'）→ POST /verify 回 409",
  "evidence":["runs/R4/f-agent-token/steps.json step=agent-estop-set @2026-09-07T09:09:59Z status=200 actor=agent","runs/R4/c-claude-write/restart-steps.json resumed-get state=cancelled closedAt=09:09:59.231260Z（同一秒）","runs/R4/c-claude-write/verify-after-restart.json 409 'only a claimed-completed session can be verified'"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"3"},
 {"id":"D13","title":"user-memory／preference 層沒有接上 supersede／conflict 機制：矛盾的偏好會同時進入每一次 Context Bundle，新舊判斷完全外包給下游 LLM 的文字推論（知識層已有完整狀態機，只是未接通）",
  "severity":"low",
  "location":"crates/interaction-runtime/src/memory.rs:279-353（bundle 建構無 supersede/dedup）；對照 crates/interaction-core/src/knowledge.rs 與 crates/interaction-runtime/src/knowledge.rs:1182-1225（candidate→active→stale→disputed→superseded 已實作）",
  "repro":"建立兩筆同 layer=user-memory、同 title/tag、內容矛盾的 preference（皆明確 agentVisibility），呼叫 POST /v1/memory/context-bundle：includes 同時含兩筆，彼此無 supersededBy／conflictWith 欄位",
  "evidence":["runs/R2/step4-bundle-after-mem2.json（includes 兩筆矛盾偏好）","runs/R2/E0-05-supersede/result.json（agent 只能靠『改為』字樣自行推論新舊）","crates/interaction-runtime/src/memory.rs:279-298（排序只有 layer_rank → updated_at desc → id）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"4"},
 {"id":"D14","title":"已 claimed-completed 的 session 仍可收新任務並真的執行（by-design），但 GET /v1/agent-sessions/{id} 的 state 全程不反映該次執行——觀測性缺口，不是行為缺陷",
  "severity":"low",
  "location":"crates/interaction-core/src/agent.rs:48-55（is_open() 含 ClaimedCompleted，並有回歸測試 claimed_completed_is_open_not_terminal 註明『驗證與關閉是人類／runtime 的獨立步驟』）；crates/interaction-runtime/src/agents.rs:899-905（mailbox_send 只檢查 is_open）",
  "repro":"讓一個 claude session 走到 claimed-completed；對同一 sessionId 再 POST 一次 {kind:task,...}；重複 GET：state 全程停在 claimed-completed，只有輪詢 messages?direction=from-session 出現新項目才看得出有事發生",
  "evidence":["runs/R2/step5-old-session-resend.json（POST 200，contextBundle.includes=[]）","runs/R2/step5-old-session-final.json（唯一擷取到的 GET：state=claimed-completed、spentMessages=3、spentCost=0.135597——原報告聲稱的 spentMessages=4/spentCost=0.31141175 沒有任何擷取到的回應支持，已由懷疑者刪除）","crates/interaction-core/src/agent.rs:48-55 與其回歸測試"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"3"},
 {"id":"D15","title":"daemon 只處理 SIGINT 的優雅關閉；SIGTERM（一般 kill／process manager stop 的預設訊號）會跳過 InstanceLock 的 Drop，下次啟動印出 stale-lock WARN",
  "severity":"low",
  "location":"crates/interaction-cli/src/commands.rs:1608（只 await tokio::signal::ctrl_c()）；crates/interaction-runtime/src/lock.rs:84-94（impl Drop for InstanceLock，未捕捉的 SIGTERM 不會執行）",
  "repro":"啟動 interact-ai serve，取得 PID，kill -TERM <pid>；程序立即消失且不印 shutting down；以相同 home 再次啟動會印 'WARN ... reclaiming stale instance lock pid=<old>'",
  "evidence":["runs/R5/homeA/daemon-run2.log:1","runs/R5/homeB/daemon-run2.log:1","crates/interaction-cli/src/commands.rs:1608；crates/interaction-runtime/src/lock.rs:84-94"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
 {"id":"D16","title":"codex 子程序 stderr 被完全丟棄，JSON-RPC 協定層錯誤（例如 D4 的無效 decision 值）在 daemon.log 留不下任何痕跡",
  "severity":"low",
  "location":"crates/interaction-agent-gateway/src/codex.rs:176-181（while let Ok(Some(_)) = lines.next_line().await {}，註解：stderr 診斷輸出吞掉避免管線塞住）",
  "repro":"跑 D4 的 deny 案例後 grep -iE 'error|reject|approval|decision' <out>/daemon.log → 0 筆；daemon.log 只有 4 行啟動訊息",
  "evidence":["runs/R4/a-codex-deny/daemon.log（全檔 4 行）","runs/R4/b-codex/daemon.log（同上）","crates/interaction-agent-gateway/src/codex.rs:176-181"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"1"},
 {"id":"D17","title":"測試 fixture fake_iphone 的 connect() 在任何連線失敗（含『核心暫時離線』）時 die() → process::exit(2)，導致 F-06 的裝置側恢復路徑無法用出貨 fixture 走完",
  "severity":"medium",
  "location":"crates/interaction-runtime/examples/fake_iphone.rs:112-115（fn die = eprintln!+process::exit(2)）、:158-177（fn connect 的 Err 分支呼叫 die）、:296-298（reconnect 無條件呼叫 connect）",
  "repro":"用 fake_iphone 對執行中的 daemon 配對，kill -KILL daemon 但保留 fake_iphone 存活，再對它 stdin 送 {\"op\":\"reconnect\"}：stderr 印『連不上 wss://…：Connection refused』後整個 process exit(2)，之後 daemon 重啟也無法用同一 process 重連",
  "evidence":["runs/R6/logs/phone2.stderr.log","runs/R6/logs/phone2.log:4（最後一行後 process 從 ps 消失）","crates/interaction-runtime/examples/fake_iphone.rs:177,298","runs/R6/logs/probe-{while-dead,after-restart}.json（改用自寫 WS probe 才驗到 daemon 側行為正確）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D18","title":"AX 測試輔助的 choosefile 無條件回報成功、不驗證 Open panel 是否真的導航，會產生假陽性（panel 停在記憶中的舊目錄並開字母序第一個檔）",
  "severity":"medium",
  "location":"scripts/lib/tauri-ax.applescript:51-63（Cmd-Shift-G → 固定 delay 0.5 → 輸入整段路徑 → Return → 固定 delay 1.2 → Return → 無條件 return 'selected file in owned Open panel'）",
  "repro":"IMPORT_KIND=not-a-companion-settings IMPORT_PATH=/private/tmp/aip-r7-imp2/one.json python3 <R7 out>/probe_picker.py <R7 out>/probe5 19074 → UI 仍顯示『已匯入角色設定並套用。』（解析器本應拒絕該 kind）",
  "evidence":["runs/R7/probe5/main-window-final.txt:225『已匯入角色設定並套用。』","runs/R7/probe{1,4}/prefs-final.json（companionName='' 與 2026-09-06 舊目錄的 blank-name.json 逐欄位相同）","~/Library/Preferences/dev.adaptive.interaction.desktop.plist 的 NSOSPLastRootDirectory 解碼為 .../adaptive-convergence-20260906/native-final-checkpoint/settings-legacy","apps/interaction-desktop/src/companion/settingsTransfer.ts:110-132（parseCompanionSettingsImport 對錯誤 kind 會 throw）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D19","title":"AX dump 走 System Events 的 entire contents 遍歷整個視窗，隨 session 累積而單調變慢，超過 driver 的 55 s 上限，導致 E0-08 native 的四個 sensor journey 從未跑到",
  "severity":"medium",
  "location":"scripts/lib/tauri-ax.applescript（dump handler）＋scripts/tests/tauri-mobile-sensor-walkthrough.py:225（subprocess timeout 55 s）",
  "repro":"python3 scripts/tests/tauri-mobile-sensor-walkthrough.py --app <App> --out <dir>，觀察 $.ax 的 dump 耗時 12.8→3.8→7.1→30.1→30.1→46.5→37.4→40.5 s 後超時",
  "evidence":["runs/R7/mobile/result.json（4/10 journey，312.414 s 後 dump 逾時）","runs/R7/mobile-diag1/result.json（6/10 journey，430.024 s，dump 時序遞增）","docs/releases/evidence/2026-09-06-convergence/final/native-final-checkpoint/mobile-clean/result.json（同一顆 App binary 於 2026-09-06 完成 10/10，334.4 s）"],
  "phase0MinimalFixCandidate":True,"suggestedPhase":"1"},
 {"id":"D20","title":"claude 續開的 session 在 create 回應裡 providerSessionId 仍是 null，且 record 從不保存 resumeProviderSessionId；codex 在 attach 當下就有值，兩個連接器投影時機不一致",
  "severity":"low",
  "location":"crates/interaction-runtime/src/agents.rs:547（provider_session_id: None 建檔）與 :619-621（等 connector init 事件回填）；CreateAgentSession.resume_provider_session_id（agents.rs:277）未寫進 AgentSessionRecord",
  "repro":"cd <R8 out>; python3 guard_probe.py --agent claude-code --port 19084 --home \"$PWD/claude/home\" --workdir \"$PWD/claude/workdir\" --resume-id <psid> --out \"$PWD/guard-claude\"；三個被接受的續開 session，create 回應的 providerSessionId 都是 null",
  "evidence":["runs/R8/guard-claude/raw.json $.probes[?(@.name=='ttl-narrower')].record.providerSessionId → null","runs/R8/claude/raw.json $.s2.createRecord.providerSessionId → null，而 $.cases.S2T1.providerSessionId → 'e63b51f8-...'","runs/R8/codex/raw.json $.s2.createRecord.providerSessionId → '01a07b22-...'（對照）"],
  "phase0MinimalFixCandidate":False,"suggestedPhase":"2"},
]

blockers = [
 {"what":"真 iPhone 簽章：iPhone 11「Alex」已連線（available (paired)）且 Developer Mode enabled，但 Xcode 的 IDEProvisioningTeams 為空（keychain 內雖有 Apple Development 憑證，但那不是 xcodebuild -allowProvisioningUpdates 讀的 store），apps/interaction-ios/scripts/device-build.sh --check-only 卡在 step 3/5",
  "humanActionNeeded":"人類在 Xcode → Settings → Accounts 登入 Apple ID 並選 Team，之後重跑 device-build.sh --check-only 通過再做真機 E2E",
  "affects":["E0-08 real-iphone","任何真機驗收欄位"]},
 {"what":"macOS 合成鍵盤事件遺失：AppleScript keystroke 打進 Tauri WebView 會非決定性掉字（兩次執行分別得到 'Native fixture codex can' 與 'Native fixture code'，osascript 全部 exit 0）。到底發生在 System Events 的事件投遞或 WebView/React 受控輸入未定；本輪不得改 repo 檔案故未進一步定位",
  "humanActionNeeded":"在低負載機器上重跑以區分負載因素；或授權修改 scripts/tests/tauri-work-cancel.py 改用剪貼簿貼上／逐字元驗證後再跑 E0-03 native",
  "affects":["E0-03 native-desktop","E0-02 native 派工"]},
 {"what":"NSOpenPanel 記憶目錄＋未驗證的 choosefile：Open panel 停在 2026-09-06 的目錄，AX helper 無條件回報成功，使 native 匯入案例無法驗證，且可能讓過去的綠燈變成假陽性",
  "humanActionNeeded":"授權修改 scripts/lib/tauri-ax.applescript 加上『確認選到的檔名』斷言，並重新驗證 2026-09-06 的 settings-clean／settings-legacy 綠燈",
  "affects":["E0-11 native-desktop"]},
 {"what":"磁碟只剩約 12 GB：本輪禁止 cargo build／pnpm build，因此原生 App 無法從 HEAD 重建。所有 native-desktop 結果綁在 2026-09-06 的 bundle（Info.plist 0.7.0，appSourceRef 3b375bde 不是 HEAD 的祖先）",
  "humanActionNeeded":"清出磁碟空間後從 HEAD 重建 apps/interaction-desktop，再重跑 native 基線",
  "affects":["E0-01 native-desktop","E0-03 native-desktop","E0-08 native-desktop","E0-11 native-desktop"]},
 {"what":"Claude 額度／冷啟動：R1 的五次 claude 執行從 task-sent 到 active 一律約 61–65 s；上一輪 restart-claude-kill 的 session 送出任務後 21 s 仍是 created 且 provider log 沒有任何 assistant 紀錄（時間接近台北中午額度重置窗口，合理但未證實）",
  "humanActionNeeded":"避開額度重置窗口重跑一次同型測試並開 debug 級 daemon 日誌，或改用不受額度影響的帳號，才能判斷 61 s 冷啟動是否為產品層問題",
  "affects":["E0-02","E0-03","E0-04（未進 active 的那一次）","任何有時間斷言的 case"]},
 {"what":"共用機器＋多個並行 agent：整輪期間有其他 agent 的 interact-ai daemon／claude -p／codex app-server 同時在跑（各回合的懷疑者分別點名 PID 17566／33157／40729／44270／67267／68328／71157／86343／4164／6757／35056 等，皆屬其他 out 目錄），所有 ps 斷言都必須依 ppid／pgid 鏈過濾",
  "humanActionNeeded":"人類決定這些 sibling run 的殘留 daemon 由誰回收；本輪任何 agent 都不得 pkill -f interact-ai",
  "affects":["所有以子程序存活與否為證據的 case"]},
]

def m(run, agent, connector, actual, reasoning, cost, dur):
    return {"run":run,"agent":agent,"connectorVersion":connector,"requestedModel":"not-specifiable-via-gateway",
            "actualModel":actual,"source":"provider-local-log (not via gateway)","reasoning":reasoning,
            "costOrTokens":cost,"durationSeconds":dur}

CC="Claude Code CLI 2.1.263 (claude -p --input-format stream-json --output-format stream-json --safe-mode)"
CX="Codex CLI 0.153.4 (codex app-server JSON-RPC v2)"

models = [
 m("prior/claude-smoke-1 (E0-02)","claude-code",CC,"claude-fable-5-1","permissionMode=plan","spentCost 0.14471075 USD, spentMessages 2",11.2),
 m("prior/codex-smoke-1 (E0-02, 不核可)","codex",CX,"gpt-6-astra","reasoning_effort=medium; approval_policy=untrusted; sandbox=read-only","spentCost 0.0（指令從未執行）",303.34),
 m("prior/codex-smoke-2 (E0-02, 核可)","codex",CX,"gpt-6-astra","reasoning_effort=medium","spentCost 0.0（codex 連接器從不回報成本）, spentMessages 4",17.01),
 m("prior/claude-cancel-1 (E0-03)","claude-code",CC,"unknown（turn 在第一個 assistant 事件前被中斷，provider log 無 model 欄）","permissionMode=plan","unknown（spentCost 0.0；失敗分支丟棄 total_cost_usd）",15.31),
 m("prior/codex-cancel-1 (E0-03)","codex",CX,"gpt-6-astra","reasoning_effort=null（summary=auto）","unknown（rollout token_count 只有 rate_limits）",15.46),
 m("prior/multi-C-claude-x2 i=0 (E0-06)","claude-code",CC,"claude-fable-5-1","permissionMode=plan","costUsd 0.13904425",12.47),
 m("prior/multi-C-claude-x2 i=1 (E0-06, 被中斷)","claude-code",CC,"unknown（中斷於第一個 assistant 事件前）","permissionMode=plan","spentCost 0.0",12.47),
 m("prior/multi-D-codex-x2 i=0 (E0-06)","codex",CX,"gpt-6-astra","reasoning_effort=medium","spentCost 0.0, spentMessages 4",16.73),
 m("prior/multi-D-codex-x2 i=1 (E0-06, 被中斷→cancelled)","codex",CX,"gpt-6-astra","reasoning_effort=medium","spentCost 0.0",16.73),
 m("prior/multi-E i=0 claude (E0-07, 被中斷)","claude-code",CC,"unknown（中斷於 assistant 事件前）","permissionMode=plan","spentCost 0.0",17.53),
 m("prior/multi-E i=1 codex (E0-07)","codex",CX,"gpt-6-astra","reasoning_effort=medium","spentCost 0.0, spentMessages 4",17.53),
 m("prior/restart-claude-kill (E0-04)","claude-code",CC,"unknown（provider log 無 assistant 紀錄；21 s 內未進 active）","unknown","spentCost 0.0, spentMessages 1",28.23),
 m("prior/restart-codex-kill (E0-04)","codex",CX,"gpt-6-astra（rollout session_meta.base_instructions.provenance.model）","unknown（turn 太短，rollout 未落地 reasoning_effort）","spentCost 0.0, spentMessages 1",6.31),
 m("R1/claude-interrupt (E0-03, active 時取消)","claude-code",CC,"claude-fable-5-1","permissionMode=plan（thinking block 為空）","input 2 / cache_creation 5765 / cache_read 2800 / output 2；無 total_cost_usd；spentCost 0.0",73.61),
 m("R1/codex-interrupt (E0-03, active 時取消)","codex",CX,"gpt-6-astra","reasoning_effort=null；approval_policy=untrusted；sandbox=read-only","unknown（rollout 無 token_count）",13.93),
 m("R1/claude-close (E0-03)","claude-code",CC,"unknown（kill 先於 provider log flush）","permissionMode=plan","unknown（無 usage 紀錄）",70.57),
 m("R1/codex-close (E0-03)","codex",CX,"gpt-6-astra","reasoning_effort=null","unknown",6.83),
 m("R1/b07-claude (stop-vs-cancel)","claude-code",CC,"claude-fable-5-1","permissionMode=plan","input 2 / cache_creation 5764 / cache_read 2800 / output 2；無 total_cost_usd",71.11),
 m("R1/b07-codex (stop-vs-cancel)","codex",CX,"gpt-6-astra","reasoning_effort=null","unknown",7.46),
 m("R1/a07-claude (emergency stop)","claude-code",CC,"unknown（estop kill 先於 provider log flush）","permissionMode=plan","unknown；spentCost 0.0",69.4),
 m("R2/E0-05-delivery-claude","claude-code",CC,"claude-fable-5-1","permissionMode=plan","costUsd 0.135597",9.5),
 m("R2/E0-05-supersede","claude-code",CC,"claude-fable-5-1","permissionMode=plan","costUsd 0.142408",10.05),
 m("R2/E0-05-delete-newtask","claude-code",CC,"claude-fable-5-1","permissionMode=plan","costUsd 0.128869",8.04),
 m("R2/E0-05-old-context-limit（(a) 對已 claimed-completed session 重送 ＋ (b) resume 續開）","claude-code",CC,"claude-fable-5-1","permissionMode=plan","(b) costUsd 0.0242975（實際擷取）；(a) 的增量未被任何擷取到的回應記錄——原報告的 spentCost 0.31141175 已由懷疑者刪除，唯一擷取到的 GET 為 spentMessages 3 / spentCost 0.135597",85.0),
 m("R3/claude-followup（2 輪，含 30 s 人類延遲）","claude-code","Claude Code CLI 2.1.263（claude -p ... --safe-mode --permission-mode plan --tools Read,Glob,Grep）","claude-fable-5-1","permissionMode=plan","USD 0.18877375（turn1 0.0812 ＋ turn2 0.1076）",43.94),
 m("R3/codex-followup（2 輪）","codex",CX,"gpt-6-astra","reasoning_effort=medium","USD 0.0（連接器不回報）；token 數 unknown（未觀察到 tokenUsage 事件）",42.99),
 m("R3/manual-report（人工 waiting-for-input 後送真任務）","claude-code",CC,"unknown（本 case 未讀 provider log 取 model，誠實記 unknown）","unknown","spentCost 0.141284",8.0),
 m("R4/a-codex-deny (E0-10 K-06)","codex",CX,"gpt-6-astra","unknown（rollout turn_context 無 reasoning_effort）；approval_policy=untrusted；sandbox=read-only","rollout total_token_usage: input 49853 / cached 25856 / output 91 / total 49944；gateway 無 costUsd",16.32),
 m("R4/b-claude 唯讀收到寫檔任務","claude-code",CC,"claude-fable-5-1","permissionMode=plan；thinking_tokens 186","costUsd 0.19381275；最後一則 usage input 32 / cache_read 8908 / output 673",28.0),
 m("R4/b-codex 唯讀＋deny","codex",CX,"gpt-6-astra","reasoning_output_tokens 24；rollout 無 reasoning_effort 欄","total_token_usage: input 49869 / cached 37632 / output 129 / total 49998",20.43),
 m("R4/c-claude-write 授權寫入","claude-code",CC,"claude-fable-5-1","permissionMode=acceptEdits（授權真的下放到工具集）","costUsd 0.1683105",10.24),
 m("R4/c-codex-write 授權寫入＋核可","codex",CX,"gpt-6-astra","unknown（rollout 無 reasoning_effort）；sandbox=workspace-write（writable_roots 含使用者全域三個目錄）","total_token_usage: input 51384 / cached 38400 / output 69 / total 51453",15.09),
 m("R4/d-resume 唯讀續開（同一 provider thread 第二輪）","claude-code",CC,"claude-fable-5-1","permissionMode 由 acceptEdits 降回 plan；thinking_tokens 145","record.budget.spentCost 0.33158（累計）；最後一則 usage input 32 / cache_read 11382 / output 495",62.0),
 m("R8/claude S1 多輪（K-04，2 輪）","claude-code",CC,"claude-fable-5-1","permissionMode=plan；turn1 thinking_tokens 259、turn2 0","USD 0.27653525（turn1 0.129469 ＋ turn2 0.14706625）",62.8),
 m("R8/claude S2 resume ＋ argv probe（重啟後再續接）","claude-code",CC,"claude-fable-5-1","permissionMode=plan（argv 顯式 --permission-mode plan、--tools Read,Glob,Grep）","USD 0.04128（S2 0.01802475 ＋ argv probe 0.02325525）；durationSeconds 只涵蓋 S2，argv probe 未計時",5.94),
 m("R8/codex S1 多輪（K-04，2 輪）","codex",CX,"gpt-6-astra","reasoning_effort=medium；approval_policy=untrusted；sandbox=read-only","USD unknown（不回報）；token_count turn1 total 24917、turn2 累計 55195",10.66),
 m("R8/codex S2 resume ＋ argv probe","codex",CX,"gpt-6-astra","reasoning_effort=medium（續接輪 turn_context 仍是 read-only/untrusted）","USD unknown；token_count 續接輪 total 35618、重啟後續接輪 36288",8.75),
]

nexttasks = [
 "crates/interaction-agent-gateway/src/claude.rs：比照 codex_exec.rs:253-258 加 per-turn cancel_requested: Arc<AtomicBool>（在 ClaudeHandle::interrupt claude.rs:354 先 store(true)，在 stdout task claude.rs:213-231 把 TaskFailed 換成 GatewayEvent::TaskCancelled，並在 send_user_message claude.rs:325-333 重置），parse_claude_line 維持純函式；新增回歸測試 crates/interaction-runtime/tests/gateway_loop.rs::claude_interrupt_reports_cancelled_not_failed（對稱於既有的 codex 斷言 gateway_loop.rs:1826-1829），並在 crates/interaction-runtime/tests/fixtures/fake_claude.sh 加 SIGINT trap 讓它印一行 result/error_during_execution 再退出",
 "crates/interaction-runtime/src/agents.rs:1371-1379：close 的 SSE 投影改為輸出 record 的真實終局狀態（或另加 closed:true 欄位），新增單元測試 close_projection_preserves_failed_state；同步檢查 apps/interaction-desktop/src/statusProjection/workState.ts 的對照",
 "crates/interaction-runtime/src/agents.rs:1209-1218：把連接器的失敗原因寫進 record.detail（並考慮補一則 from-session failure 訊息），新增測試 report_agent_session_sets_detail_on_failure",
 "crates/interaction-agent-gateway/src/codex.rs:643-644：Deny 的 wire 值由 \"reject\" 改為 \"decline\"，加一支對 codex-schema-0.153.4 列舉的編譯期／單元斷言，並重跑真 agent 迴歸 python3 harness/agent_smoke.py --agent codex --approve deny 確認 rollout 不再出現 Rejected(\"approval request failed\")",
 "crates/interaction-agent-gateway/src/codex.rs:176-181：把 codex 子程序 stderr 以 warn/debug 導進 daemon.log（有界、不阻塞），讓協定層錯誤留痕",
 "crates/interaction-agent-gateway/src/codex.rs:166-169：研究 codex app-server 是否有可確定性關閉 MCP/plugin 的旗標或獨立 CODEX_HOME；有就比照 claude.rs:82-84 補上並加 argv 斷言測試，沒有就把『codex session 會啟動使用者設定的 MCP server 與 computer-use helper、任務全文出現在 process argv』寫進 CHANGELOG.md 與 docs/releases/v0.8.0-known-limitations.md",
 "crates/interaction-agent-gateway/src/codex.rs:315-340：thread/start 與 thread/resume 明確送 writable_roots=[resolvedWorkdir] 以覆寫使用者全域設定（需先做產品決策：使用者 codex 設定 vs 平台 session 授權誰優先），並加一支讀 rollout turn_context.sandbox_policy.writable_roots 的驗收斷言",
 "crates/interaction-agent-gateway/src/codex.rs:250-263 與 :623-660：依 method 分派 ServerRequest，把 item/tool/requestUserInput 對應到 GatewayEvent::TaskWaitingForInput，並以 ToolRequestUserInputResponse 的 {answers:{…}} shape 回覆；同時讓 approval_summary（codex.rs:432-445）保留問題文字",
 "crates/interaction-runtime/src/agents.rs:453-468：resume guard 的接受與拒絕都寫 store.audit（含放寬了哪一項、接續的 providerSessionId），新增測試 resume_guard_writes_audit",
 "crates/interaction-runtime/examples/fake_iphone.rs:158-177/296-298：connect() 改回傳 Result，reconnect() 在失敗時發一個可恢復事件而不是 process::exit(2)；之後用出貨 fixture 重跑 E0-08 F-06 的裝置側路徑",
 "scripts/lib/tauri-ax.applescript:51-63：choosefile 必須驗證 Open panel 真的導航到指定檔（斷言選到的檔名），再重跑 scripts/tests/tauri-settings-walkthrough.py；並重新驗證 docs/releases/evidence/2026-09-06-convergence/final/native-final-checkpoint/settings-{clean,legacy} 的綠燈是否為假陽性",
 "scripts/lib/tauri-ax.applescript 的 dump handler：把 AX 遍歷縮到子樹（或在 scripts/tests/tauri-mobile-sensor-walkthrough.py:225 提高 55 s 上限並分段 dump），讓 E0-08 native 的四個 sensor journey（sensor-stop-unknown / sensor-direct-remove-retains-unknown / sensor-unknown-after-daemon-restart / sensor-global-stop-separate-fixture）真的跑到",
 "scripts/tests/tauri-work-cancel.py:169-175：把 AX fill 的 keystroke 改成剪貼簿貼上或逐字元驗證重試，消除掉字，再重跑 E0-03 native（Codex turn 取消＋Claude fixture 關閉後 process group 死亡）",
 "補跑本輪缺的執行期證據：(a) python3 harness/restart_test.py --signal TERM 對 claude-code 與 codex 各一次；(b) codex 的 300 s APPROVAL_TTL 自動拒絕（從 approval-request 自己的建立時間起算超過 300 s，斷言 approvalAutoDenied 與 delivered:false）；(c) 併發上限：對同一 daemon 連開 9 個 plain session 斷言第 9 個 4xx 帶 'too many open agent sessions (8 ≥ 8)'，另外 5 個共用 rootTaskId 的 delegation create 斷言第 5 個引用 'max_parallel 4'；(d) codex 版的 E-09（resume 後已刪記憶是否殘留）",
 "docs/releases/v0.8.0-known-limitations.md：重申 v0.4 就記錄在 CHANGELOG.md:1846/1859 的『agent 子程序孤兒回收為 best-effort、只在下次重啟才 reap』，並新增本輪確認的 codex MCP/writable_roots 邊界",
 "crates/interaction-cli/src/commands.rs:1608：同時處理 SIGTERM 與 SIGINT，讓 InstanceLock 的 Drop 在一般 kill 下也會執行（消除 reclaiming stale instance lock 的雜訊）",
 "在磁碟清出空間後，從 HEAD 重建 apps/interaction-desktop 並重跑 R7 的四支 native driver，讓 native 基線綁定在 HEAD 而不是 2026-09-06 的 0.7.0 bundle",
]

dual = ("Claude Code 走完了派工／多輪／原生 --resume 續接／唯讀與授權寫入／human verify／撤銷／過期／重啟恢復／記憶與 E-09，"
        "唯一的 product-failed 是人類 interrupt 被記成 failed（5/5 重現，連接器完全產不出 cancelled，且 close 投影又把它壓成 closed、record 上沒有任何原因）；"
        "Codex 走完了同一組流程且 interrupt→cancelled 正確、thread/resume 授權重新上鎖，但有兩個 product-failed 級缺陷：deny 送出的 wire 值 \"reject\" 不在 0.153.4 的合法列舉內（安全結果靠 provider fail-closed 而非我們送對值），"
        "以及連接器沒有 MCP/plugin 封鎖、唯讀 session 仍會啟動使用者的 chrome-devtools-mcp／codegraph／ChatGPT computer-use helper 並把任務全文暴露在 process argv；"
        "兩個平台共同 not-implemented 的是『停止這一輪但保留 session』與 waiting-for-input 的自動偵測。")

multi = ("多 Session 在 runtime 層是乾淨的：同型 claude×2、同型 codex×2、跨型 claude+codex 三種配對各跑一次，"
         "結果不交叉洩漏（每個 summary 只含自己 workdir 的暗號）、SSE 的 session 範圍事件在 134/151/146 行中 0 筆 sessionId 混淆、"
         "取消其中一個不影響另一個的時間線、核可只作用在發出請求的那個 session、被取消的記錄也留在 list 不靜默消失（status.agentSessions 只是開啟中計數）；"
         "唯一沒驗到的是併發上限本身（max_sessions=8／max_parallel=4 在原始碼確實實作，但本輪最多只跑 2 個並行 session，改判 needs-environment 而非 not-implemented）。")

out = {"markdown":md,"table":table,"productDefects":defects,"environmentBlockers":blockers,
       "modelTable":models,"dualPlatformVerdict":dual,"multiSessionVerdict":multi,"nextTasks":nexttasks}
p = base/"e2e-baseline.json"
p.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
print("wrote", p, p.stat().st_size, "bytes")
print("table", len(table), "defects", len(defects), "blockers", len(blockers), "models", len(models), "nextTasks", len(nexttasks))
