// GENERATED by scripts/aip-codegen.mjs — do not edit.
// Source of truth: schemas/aip-1.0.schema.json (generated from crates/interaction-aip).
// Regenerate with `pnpm aip:codegen`; CI verifies with `pnpm aip:check`.
//
// 契約：docs/aip/README.md。行為（驗證、去重、協商、離線政策）在 ./envelope.ts，不在這裡。

/** 任意 JSON 值。未知欄位一律保留成這個型別，不猜、不丟。 */
export type AipJsonValue =
  | null
  | boolean
  | number
  | string
  | AipJsonValue[]
  | { [key: string]: AipJsonValue };

/**
 * 十二種 message type。未知值反序列化成 [`MessageType::Unknown`]，**不得執行**（§4.1）。
 */
export type KnownMessageType =
  | "event"
  | "command"
  | "query"
  | "response"
  | "result"
  | "state"
  | "cancel"
  | "approval-request"
  | "approval-result"
  | "error"
  | "heartbeat"
  | "capability";

/** 未知值保留原字串供稽核，但永不執行（AIP §4.1）。 */
export type MessageType = KnownMessageType | (string & {});

/**
 * 訊息／能力的參與方種類。未知值 → [`PartyKind::Unknown`]（保留原字串）。
 */
export type KnownPartyKind =
  | "runtime"
  | "session"
  | "device"
  | "renderer"
  | "human-surface"
  | "human"
  | "agent";

/** 未知值保留原字串供稽核，但永不執行（AIP §4.1）。 */
export type PartyKind = KnownPartyKind | (string & {});

export const AIP_KNOWN_PARTY_KINDS: readonly KnownPartyKind[] = [
  "runtime",
  "session",
  "device",
  "renderer",
  "human-surface",
  "human",
  "agent",
];

/**
 * 穩定錯誤碼；1.x 內只增不改。未知值保留原字串。
 */
export type KnownErrorCode =
  | "schema-invalid"
  | "unsupported-version"
  | "unsupported-message-type"
  | "unknown-name"
  | "unsupported-capability"
  | "payload-too-large"
  | "message-too-large"
  | "expired"
  | "duplicate"
  | "revision-mismatch"
  | "sequence-gap"
  | "identity-mismatch"
  | "not-a-member"
  | "scope-denied"
  | "rate-limited"
  | "session-not-found"
  | "session-disabled"
  | "cancelled"
  | "internal";

/** 未知值保留原字串供稽核，但永不執行（AIP §4.1）。 */
export type ErrorCode = KnownErrorCode | (string & {});

/**
 * `result.payload.status` 的十二種值。
 */
export type Outcome =
  | "received"
  | "accepted"
  | "acknowledged"
  | "applied"
  | "observed"
  | "claimed-completed"
  | "verified"
  | "rejected"
  | "expired"
  | "cancel-requested"
  | "cancel-confirmed"
  | "failed";

export const AIP_OUTCOMES: readonly Outcome[] = [
  "received",
  "accepted",
  "acknowledged",
  "applied",
  "observed",
  "claimed-completed",
  "verified",
  "rejected",
  "expired",
  "cancel-requested",
  "cancel-confirmed",
  "failed",
];


export type OfflinePolicy =
  | "drop-if-offline"
  | "expire-by-deadline"
  | "queue-idempotent"
  | "require-reconfirmation"
  | "state-reconcile";

export const AIP_OFFLINE_POLICYS: readonly OfflinePolicy[] = [
  "drop-if-offline",
  "expire-by-deadline",
  "queue-idempotent",
  "require-reconfirmation",
  "state-reconcile",
];


export type EvidenceClass =
  | "unit"
  | "contract"
  | "fixture"
  | "simulator"
  | "integration"
  | "browser"
  | "real-agent"
  | "real-device"
  | "real-hardware"
  | "unverified";

export const AIP_EVIDENCE_CLASSS: readonly EvidenceClass[] = [
  "unit",
  "contract",
  "fixture",
  "simulator",
  "integration",
  "browser",
  "real-agent",
  "real-device",
  "real-hardware",
  "unverified",
];

/**
 * 參與方角色。
 */
export type MemberRole =
  | "host-renderer"
  | "remote-renderer"
  | "input-device"
  | "observer";

export const AIP_MEMBER_ROLES: readonly MemberRole[] = [
  "host-renderer",
  "remote-renderer",
  "input-device",
  "observer",
];

/**
 * 同步等級（§8／character-session.md §9）。1.0 只實作 `semantic`。
 */
export type SyncClass =
  | "semantic"
  | "timeline"
  | "realtime";

export const AIP_SYNC_CLASSS: readonly SyncClass[] = [
  "semantic",
  "timeline",
  "realtime",
];

/**
 * 單一 intent 的協商結果。
 */
export type IntentSupport =
  | "exact"
  | "unsupported";

export const AIP_INTENT_SUPPORTS: readonly IntentSupport[] = [
  "exact",
  "unsupported",
];

/**
 * 參與方參照。**只是宣稱**；可信身分由 Transport 綁定後比對（§5）。
 */
export interface Party {
  kind: PartyKind;
  id: string;
}

/**
 * AIP 1.0 訊息信封。未知頂層選填欄位保留在 `extra`（round-trip 不遺失、不執行）。
 */
export interface Envelope {
  specVersion: string;
  messageId: string;
  messageType: MessageType;
  name: string;
  source: Party;
  occurredAt: string;
  baseRevision?: number | null;
  causationId?: string | null;
  consentGrantId?: string | null;
  correlationId?: string | null;
  expiresAt?: string | null;
  payload?: AipJsonValue;
  sequence?: number | null;
  sessionId?: string | null;
  target?: Party | null;
  /** 未知的頂層選填欄位：保留、忽略，round-trip 不遺失（AIP §1）。 */
  [key: string]: unknown;
}

/**
 * `error.payload`。`message` ≤ 200 字、不回顯輸入；`details` 不得含 secret／路徑／token。
 */
export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  details?: Record<string, AipJsonValue> | null;
}


export interface CapabilityLimits {
  maxMessageBytes?: number | null;
}

/**
 * `capability` 宣告 payload（member → host）。未知鍵保留在 `extra`。
 */
export interface CapabilityAnnouncement {
  features?: Record<string, AipJsonValue>;
  /**
   * 可產生的 event name。
   */
  inputs?: string[];
  /**
   * 可呈現的 Behavior Intent 名稱。
   */
  intents?: string[];
  limits?: CapabilityLimits | null;
  profiles?: string[];
  role?: MemberRole | null;
  specVersions?: string[];
  syncClasses?: SyncClass[];
}

/**
 * host 回的協商結果（`capability` payload，host → member）。
 */
export interface NegotiatedCapabilities {
  specVersion: string;
  newerMinor: boolean;
  role: MemberRole;
  syncClass: SyncClass;
  intents: Record<string, IntentSupport>;
  inputs: string[];
  unsupportedInputs: string[];
  limits: CapabilityLimits;
}

/** 本實作宣告的 spec 版本。major 不同一律拒絕（AIP §4.1）。 */
export const AIP_SPEC_VERSION = "aip/1.0" as const;

/** 十二種 message type（AIP §2.1）。 */
export const AIP_MESSAGE_TYPES: readonly KnownMessageType[] = [
  "event",
  "command",
  "query",
  "response",
  "result",
  "state",
  "cancel",
  "approval-request",
  "approval-result",
  "error",
  "heartbeat",
  "capability",
];

/** 穩定錯誤碼（AIP §12）。 */
export const AIP_ERROR_CODES: readonly KnownErrorCode[] = [
  "schema-invalid",
  "unsupported-version",
  "unsupported-message-type",
  "unknown-name",
  "unsupported-capability",
  "payload-too-large",
  "message-too-large",
  "expired",
  "duplicate",
  "revision-mismatch",
  "sequence-gap",
  "identity-mismatch",
  "not-a-member",
  "scope-denied",
  "rate-limited",
  "session-not-found",
  "session-disabled",
  "cancelled",
  "internal",
];

/** 上限常數（AIP §11）。所有集合、訊息、字串都有界。 */
export const AIP_LIMITS = {
  dedupeRing: 256,
  defaultIntentTtlMs: 10000,
  defaultInteractionTtlMs: 5000,
  eventLogRing: 512,
  maxClockSkewMs: 30000,
  maxIdChars: 128,
  maxJsonDepth: 8,
  maxMembers: 16,
  maxMessageBytes: 65536,
  maxNameChars: 128,
  maxPayloadBytes: 32768,
  maxStringChars: 2000,
} as const;
